version: '3.3'

services:
  redis-master: 
    image: redis
    networks:
      - db
  redis-slave:
    image: redis
    command: redis-server --slaveof redis-master 6379
    deploy:
      mode: replicated
      replicas: 5
    networks:
      - db
  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    networks:
      - db
      - frontend
    deploy:
      mode: replicated
      replicas: 5
    environment: 
      - VIRTUAL_HOST=localhost
  lb:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    networks:
      - frontend

networks:
  db: {}  
  frontend: {}
